PasswordRepository/PasswordRepository.ASP/Controllers/AccountsController.cs
using PasswordRepository.Core;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PasswordRepository.ASP
{
	public class AccountsController : Controller
	{
		public async Task<ActionResult> IndexAsync()
		{
			return View("Index", await CoreDI.DataStore.GetAccountsDetailsAsync());
		}

		public ActionResult About()
		{
			ViewBag.Message = "It consists of two user interfaces: an ASP.NET MVC website and a WPF Windows application. Both interfaces interact with a shared C# codebase and use MS SQL Server with Entity Framework 6 (EF6) for data persistence. The application supports the secure hashing of passwords and provides CRUD operations for password management.";
			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Vlad Kontsevich";
			return View();
		}

		public ActionResult Create()
		{
			return View("Details");
		}

		public ActionResult Edit(int id, string accountName, DateTime lastUpdated, string comments, string password)
		{
			var account = new Account
			{
				Id = id,
				AccountName = accountName,
				LastUpdated = lastUpdated,
				Comments = comments,
				Password = EncryptionHelper.Decrypt(password)
			};
			return View("Details", account);
		}

		[HttpPost]
		public async Task<ActionResult> SaveAsync(Account account)
		{
			account.Password = EncryptionHelper.Encrypt(account.Password);
			account.LastUpdated = DateTime.Now;

			var isSaved = await CoreDI.DataStore.SaveAccountAsync(account);
			return Json(new { success = isSaved });
		}

		[HttpPost]
		public async Task<ActionResult> DeleteAsync(Account account)
		{
			var isDeleted = await CoreDI.DataStore.DeleteAccountAsync(account);
			return Json(new { success = isDeleted });
		}
	}
}

PasswordRepository/PasswordRepository.ASP/Views/Accounts/About.cshtml
@{
	ViewBag.Title = "Password Repository is a simple application designed to securely store and manage passwords.";
}
<main aria-labelledby="title">
	<h3 id="title">@ViewBag.Title</h3>
	<p>@ViewBag.Message</p>

	<h4>Features</h4>
	<h5>Dual UI Fronts</h5>
	<ul>
		<li>ASP.NET MVC website</li>
		<li>WPF Windows application</li>
	</ul>
	<h5>Secure Password Storage</h5>
	<ul>
		<li>Passwords are hashed before saving to the database using AES</li>
		<li>Passwords are unhashed when retrieved for display using AES</li>
	</ul>
	<h5>CRUD Operations</h5>
	<ul>
		<li>Insert, Edit, Delete password entries</li>
	</ul>
	<h5>Real-Time Updates</h5>
	<ul>
		<li>ASP.NET MVC website performs all operations using AJAX</li>
	</ul>
	<h5>Detailed Information</h5>
	<ul>
		<li>List view with account names, last update date, comments</li>
		<li>Detail view for creating and updating accounts</li>
	</ul>
</main>

PasswordRepository/PasswordRepository.ASP/Views/Accounts/Contact.cshtml
@{
	ViewBag.Title = "VelScorp Contact";
}
<main aria-labelledby="title">
	<h2 id="title">@ViewBag.Title.</h2>
	<h3>@ViewBag.Message</h3>

	<address>
		Wrocław<br />
		Poland<br />
	</address>

	<address>
		<strong>E-Mail:</strong><p>ukantsevich@gmail.com</p>
		<strong>GitHub:</strong> <a href="https://github.com/VelSkorp">github.com/VelSkorp</a><br />
		<strong>LeetCode:</strong> <a href="https://leetcode.com/u/VelSkorp/">leetcode.com/u/VelSkorp</a><br />
		<strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/vlad-kontsevich/">linkedin.com/in/vlad-kontsevich/</a>
	</address>
</main>

PasswordRepository/PasswordRepository.ASP/Views/Accounts/Details.cshtml
@model PasswordRepository.Core.Account

@{
	ViewBag.Title = "Details";
}

<h2>Account Details</h2>

@using (Html.BeginForm("SaveAsync", "Accounts", FormMethod.Post))
{
	@Html.HiddenFor(model => model.Id)
	@Html.Partial("_AccountForm", Model ?? new PasswordRepository.Core.Account())
}

@section scripts {
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script>
		$(function () {
			$('form').submit(function (event) {
				event.preventDefault();

				var formData = $(this).serialize();

				$.ajax({
					url: $(this).attr('action'),
					type: $(this).attr('method'),
					data: formData,
					success: function (response) {
						if (response.success)
						{
							window.location.href = '@Url.Action("IndexAsync", "Accounts")';
							alert('Account saved successfully.');
						}
						else
						{
							alert('Failed to save the account.');
						}
					},
					error: function (xhr, status, error) {
						console.error(xhr.responseText);
					}
				});
			});
		});
	</script>
}

PasswordRepository/PasswordRepository.ASP/Views/Accounts/Index.cshtml
@model IEnumerable<PasswordRepository.Core.Account>

@{
	ViewBag.Title = "Password Repository";
}

<h2>Password Repository</h2>

<p>
	@Html.ActionLink("Create New", "Create")
</p>

<table class="table" id="passwordTable">
	<thead>
		<tr>
			<th>Account name</th>
			<th>Last updated</th>
			<th>Comments</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr data-id="@item.Id"
				data-accountname="@item.AccountName"
				data-lastupdated="@item.LastUpdated"
				data-comments="@item.Comments"
				data-password="@item.Password"
				class="passwordRow">
				<td>@item.AccountName</td>
				<td>@item.LastUpdated.ToString()</td>
				<td>@item.Comments</td>
				<td>
					@Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning editLink", data_id = item.Id, data_accountname = item.AccountName, data_lastupdated = item.LastUpdated, data_comments = item.Comments, data_password = item.Password, onclick = "return;" })
					@Html.ActionLink("Delete", "DeleteAsync", new { id = item.Id }, new { @class = "btn btn-danger deleteLink", data_accountname = item.AccountName, data_lastupdated = item.LastUpdated, data_comments = item.Comments, data_password = item.Password, onclick = "return;" })

				</td>
			</tr>
		}
	</tbody>
</table>

@section scripts {
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script defer>
		$(function () {
			$('.deleteLink').click(function (event) {
				event.preventDefault();

				var deleteUrl = $(this).attr('href');
				var accountId = $(this).data('id');
				var accountName = $(this).data('accountname');
				var lastUpdated = $(this).data('lastupdated');
				var comments = $(this).data('comments');
				var password = $(this).data('password');
				if (confirm('Are you sure you want to delete this item?')) {
					$.ajax({
						url: deleteUrl,
						type: 'POST',
						data:
						{
							id: accountId,
							AccountName: accountName,
							LastUpdated: lastUpdated,
							Comments: comments,
							Password: password
						},
						success: function (response) {
							if (response.success) {
								window.location.href = '@Url.Action("IndexAsync", "Accounts")';
								alert('Account deleted successfully.');
							} else {
								alert('Failed to delete the account.');
							}
						},
						error: function (xhr, status, error) {
							console.error(xhr.responseText);
						}
					});
				}
			});

			function handleEdit(event) {
				event.preventDefault();

				var editUrl = $(this).attr('href') || $(this).data('href');
				var accountId = $(this).data('id');
				var accountName = $(this).data('accountname');
				var lastUpdated = $(this).data('lastupdated');
				var comments = $(this).data('comments');
				var password = $(this).data('password');

				window.location.href = editUrl +
					'?id=' + accountId +
					'&AccountName=' + encodeURIComponent(accountName) +
					'&LastUpdated=' + encodeURIComponent(lastUpdated) +
					'&Comments=' + encodeURIComponent(comments) +
					'&Password=' + encodeURIComponent(password);
			}

			$(document).on('click', '.editLink', handleEdit);

			$(document).on('dblclick', '#passwordTable tr', function () {
				var editLink = $(this).find('.editLink');
				if (editLink.length) {
					editLink.trigger('click');
				}
			});
		});
	</script>
}

PasswordRepository/PasswordRepository.ASP/Views/Shared/_AccountForm.cshtml
@model PasswordRepository.Core.Account

<div>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.AccountName)
		</dt>
		<dd>
			@Html.TextBoxFor(model => model.AccountName, new { @class = "form-control" })
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Comments)
		</dt>
		<dd>
			@Html.TextAreaFor(model => model.Comments, new { @class = "form-control" })
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Password)
		</dt>
		<dd>
			<input type="text" class="form-control" name="Password" value="@Model.Password" />
		</dd>
	</dl>
</div>

<p>
	<button type="submit" class="btn btn-warning">Save</button>
	@Html.ActionLink("Back to List", "IndexAsync", null, new { @class = "btn btn-default" })
</p>

PasswordRepository/PasswordRepository.ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - VelScorp ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Styles.Render("~/Content/Site.css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
		<div class="container">
			@Html.ActionLink("Password Repository", "IndexAsync", "Accounts", new { area = "" }, new { @class = "navbar-brand" })
			<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
					aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
				<ul class="navbar-nav flex-grow-1">
					<li>@Html.ActionLink("Accounts", "IndexAsync", "Accounts", new { area = "" }, new { @class = "nav-link" })</li>
					<li>@Html.ActionLink("About", "About", "Accounts", new { area = "" }, new { @class = "nav-link" })</li>
					<li>@Html.ActionLink("Contact", "Contact", "Accounts", new { area = "" }, new { @class = "nav-link" })</li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - VelScorp ASP.NET Application</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>